=== 1EdTech/cert-schema/cert_schema/2.0-alpha/merkleProof2017Schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "MerkleProof2017 schema",
  "description": "An extension that allows an issuer to issue an Open Badge on the blockchain and provide proof of inclusion in a blockchain transaction. This uses the Chainpoint v2.0 specification: https://chainpoint.org/",
  "type": "object",
  "definitions": {
    "JsonLdType": {
      "description": "A type or an array of types defined in a JSON-LD context file.",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      ]
    }
  },	
  "properties": {
    "type": {
      "$ref": "#/definitions/JsonLdType"
    },
    "merkleRoot": {
      "type": "string"
    },
    "targetHash": {
      "type": "string"
    },
    "proof": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "right": {
            "type": "string"
          },
          "left": {
            "type": "string"
          }
        }
      }
    },
    "anchors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "sourceId": {
            "type": "string"
          },
          "type": {
            "type": "string"
          }
        }
      }
    }
  },
  "required": ["type", "merkleRoot", "targetHash", "proof", "anchors"]
}

=== 1EdTech/cert-schema/tests/data/2.0/receipt.json
{
  "type": [
    "MerkleProof2017",
    "Extension"
  ],
  "merkleRoot": "68f3ede17fdb67ffd4a5164b5687a71f9fbb68da803b803935720f2aa38f7728",
  "targetHash": "c9ead76a54426b4ce4899bb921e48f5b55ea7592e5cee4460c86ebf4698ac3a6",
  "proof": [
    {
      "right": "7fef060cb17614fdfddd8c558e102fbb96433f5281e96c80f805459773e51163"
    }
  ],
  "anchors": [
    {
      "sourceId": "8623beadbc7877a9e20fb7f83eda6c1a1fc350171f0714ff6c6c4054018eb54d",
      "type": "BTCOpReturn"
    }
  ]
}
