=== 1EdTech/cert-schema/cert_schema/schema/1.2/blockchain-certificate-1.2.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Blockchain Certificates Version 1.2 Schema",
  "id": "https://w3id.org/blockcerts/schema/1.2/blockchain-certificate-1.2.json",
  "description": "A schema for representing certificates on the blockchain",
  "type": "object",
  "definitions": {
    "JsonLdContext": {
      "description": "A link to a valid JSON-LD context file, that maps term names to contexts. Blockchain Certificate contexts may also define JSON-schema to validate Blockchain Certificates against. In a Blockchain Certificate Object, this will almost always be a string:uri to a single context file, but might rarely be an array of links or context objects instead. This schema also allows direct mapping of terms to IRIs by using an object as an option within an array.",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "type": "string"
              },
              {
                "type": "object"
              },
              {
                "type": "array"
              }
            ]
          }
        }
      ]
    },
    "JsonLdType": {
      "description": "A type or an array of types that the Blockchain Certificate object represents. The first or only item should be 'BlockchainCertificate', and any others should each be an IRI (usually a URL) corresponding to a definition of the type itself. In almost all cases, there will be only one type: 'BlockchainCertificate'",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      ]
    },
    "CertificateDocument": {
      "$ref": "https://w3id.org/blockcerts/schema/1.2/certificate-document-1.2.json"
    },
    "BlockchainReceipt": {
      "$ref": "https://w3id.org/blockcerts/schema/1.2/blockchain-receipt-1.2.json"
    }
  },
  "properties": {
    "@context": {
      "$ref": "#/definitions/JsonLdContext"
    },
    "type": {
      "$ref": "#/definitions/JsonLdType"
    },
    "document": {
      "$ref": "#/definitions/CertificateDocument"
    },
    "receipt": {
      "$ref": "#/definitions/BlockchainReceipt"
    }
  },
  "required": [
    "@context",
    "type",
    "document",
    "receipt"
  ],
  "additionalProperties": true
}

=== 1EdTech/cert-schema/examples/1.2/sample_signed_cert-1.2.json
{
  "@context": "https://w3id.org/blockcerts/v1",
  "type": "BlockchainCertificate",
  "document": {
    "type": "CertificateDocument",
    "assertion": {
      "type": "Assertion",
      "evidence": "",
      "id": "http://www.theissuer.edu/fb9e6259-f3ee-438a-b98f-a24f54187af8",
      "image:signature": "data:image/png;base64,",
      "issuedOn": "2016-05-26T12:00:00Z",
      "uid": "fb9e6259-f3ee-438a-b98f-a24f54187af8"
    },
    "certificate": {
      "type": "Certificate",
      "description": "Certificate description",
      "image": "data:image/png;base64,",
      "issuer": {
        "type": "Issuer",
        "email": "issuer@theissuer.edu",
        "id": "https://www.theissuer.edu/issuer/the-issuer.json",
        "image": "data:image/png;base64,",
        "name": "Issuing Institution",
        "url": "http://www.theissuer.edu"
      },
      "subtitle": "2016",
      "name": "Certificate name"
    },
    "recipient": {
      "familyName": "RecipientLastName",
      "givenName": "RecipientFirstName",
      "hashed": false,
      "identity": "recipient@domain.com",
      "publicKey": "1GCrFRozNVWCqTreV7ZoXudiotknoJeXaz",
      "type": "email"
    },
    "signature": "IAhahreb77hgM9khBcWCSfwq0Qal/bzU9AzBSUMEDErTdExBRHsBH2dDmBa1NvR38wVGn70SPEglI0VIvUFc2AI=",
    "verify": {
      "attribute-signed": "uid",
      "type": "ECDSA(secp256k1)"
    }
  },
  "receipt": {
    "@context": "https://w3id.org/chainpoint/v2",
    "type": "ChainpointSHA256v2",
    "targetHash": "3e23e8160039594a33894f6564e1b1348bbd7a0088d42c4acb73eeaed59c009d",
    "merkleRoot": "d71f8983ad4ee170f8129f1ebcdd7440be7798d8e1c80420bf11f1eced610dba",
    "proof": [
      {
        "left": "ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb"
      },
      {
        "right": "bffe0b34dba16bc6fac17c08bac55d676cded5a4ade41fe2c9924a5dde8f3e5b"
      },
      {
        "right": "3f79bb7b435b05321651daefd374cdc681dc06faa65e374e38337b88ca046dea"
      }
    ],
    "anchors": [
      {
        "type": "BTCOpReturn",
        "sourceId": "b84a92f28cc9dbdc4cd51834f6595cf97f018b925167c299097754780d7dea09"
      }
    ]
  }
}
