=== 1EdTech/cert-schema/cert_schema/schema/certificate/1.2.0/certificate-document-1.2.0.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Digital Certificates Version 1.2.0 Schema",
  "id": "http://www.blockcerts.org/schema/1.2.0/blockchain-certificate-1.2.0.json",
  "description": "Digital Certificates Version 1.2.0 Schema: a schema for representing digital certificates on the blockchain",
  "type": "object",
  "definitions": {
    "JsonLdContext": {
      "description": "A link to a valid JSON-LD context file, that maps term names to contexts. Digital certificates contexts extend Open Badges contexts, and also define JSON-schema to validate digital certificates against.",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "type": "string"
              },
              {
                "type": "object"
              },
              {
                "type": "array"
              }
            ]
          }
        }
      ]
    },
    "JsonLdType": {
      "description": "A type or an array of types that the digital-certificates object represents. The first or only item should be 'issuer', and any others should each be an IRI (usually a URL) corresponding to a definition of the type itself. In almost all cases, there will be only one type: 'digital-certificate'",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      ]
    },
    "Certificate": {
      "$ref": "http://www.blockcerts.org/schema/1.2.0/certificate-1.2.0.json"
    },
    "Assertion": {
      "$ref": "http://www.blockcerts.org/schema/1.2.0/assertion-1.2.0.json"
    },
    "Issuer": {
      "$ref": "http://www.blockcerts.org/schema/1.2.0/issuer-1.2.0.json"
    },
    "VerificationObject": {
      "type": "object",
      "properties": {
        "type": {
          "title": "VerificationType",
          "type": "string",
          "enum": [
            "hosted",
            "signed",
            "ECDSA(secp256k1)"
          ]
        },
        "url": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "Recipient": {
      "type": "object",
      "properties": {
        "@type": {
          "$ref": "#/definitions/JsonLdType"
        },
        "familyName": {
          "type": "string",
          "description": "Family name of the recipient. http://schema.org/Person#familyName"
        },
        "identity": {
          "type": "string",
          "description": "String that represents a recipient's identity. By default, it is an email address."
        },
        "type": {
          "type": "string",
          "description": "Type of value in the identity field. Default is 'email'."
        },
        "hashed": {
          "type": "boolean",
          "description": "Describes if the value in the identity field is hashed or not. We strongly recommend that the issuer hash the identy to protect the recipient. Backcompatible change to allow 2 types that occurred in the wild before proper validation."
        },
        "salt": {
          "type": "string",
          "description": "per the OBI standard, if the recipient identity is hashed, then this should contain the string used to salt the hash"
        },
        "pubkey": {
          "type": "string",
          "description": "Bitcoin address (compressed public key, usually 24 characters) of the recipient."
        },
        "givenName": {
          "type": "string",
          "description": "Given name of the recipient. http://schema.org/Person#givenName"
        }
      },
      "required": [
        "@type",
        "familyName",
        "identity",
        "type",
        "hashed",
        "pubkey",
        "givenName"
      ],
      "additionalProperties": true
    }

  },
  "properties": {
    "@context": {
      "$ref": "#/definitions/JsonLdContext"
    },
    "@type": {
      "$ref": "#/definitions/JsonLdType"
    },
    "certificate": {
      "$ref": "#/definitions/Certificate"
    },
    "assertion": {
      "$ref": "#/definitions/Assertion"
    },
    "verify": {
      "$ref": "#/definitions/VerificationObject"
    },
    "recipient": {
      "$ref": "#/definitions/Recipient"
    }
  },
  "required": [
    "@type",
    "certificate",
    "assertion",
    "verify",
    "recipient"
  ],
  "additionalProperties": true
}

=== 1EdTech/cert-schema/examples/1.2.0/sample_unsigned_cert-1.2.0.json
{
  "@context": "https://raw.githubusercontent.com/digital-certificates/cert-schema/kh_receipt/cert_schema/schema/certificate/1.2.0/context.json#",
  "@type": "DigitalCertificate",
  "verify": {
    "@type": "VerificationObject",
    "signer": "https://www.theissuer.edu/keys/signing-public-key.asc",
    "attribute-signed": "uid",
    "type": "ECDSA(secp256k1)"
  },
  "recipient": {
    "@type": "Recipient",
    "type": "email",
    "familyName": "RecipientLastName",
    "hashed": false,
    "givenName": "RecipientFirstName",
    "pubkey": "n1EduLzKsTL1pM8Roz9vEV16AQnBdg9JCx",
    "identity": "recipient@domain.com"
  },
  "certificate": {
    "@type": "Certificate",
    "subtitle": "2016",
    "description": "Certificate description",
    "title": "Certificate title",
    "image:certificate": "data:image/png;base64,",
    "id": "https://www.theissuer.edu/criteria/2016/05/certificate-type.json",
    "issuer": {
      "@type": "Issuer",
      "url": "http://www.theissuer.edu",
      "name": "Issuing Institution",
      "id": "https://www.theissuer.edu/issuer/the-issuer.json",
      "image:logo": "data:image/png;base64,",
      "email": "issuer@theissuer.edu"
    }
  },
  "assertion": {
    "@type": "Assertion",
    "issuedOn": "2016-05-26T12:00:00Z",
    "image:signature": "data:image/png;base64,",
    "id": "http://www.theissuer.edu/fb9e6259-f3ee-438a-b98f-a24f54187af8",
    "uid": "fb9e6259-f3ee-438a-b98f-a24f54187af8",
    "evidence": "https://www.theissuer.edu/issuer/the-issuer.json"
  }
}
